# Generated by Django 2.2.7 on 2019-11-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='kategoria',
            fields=[
                ('idKategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='klient',
            fields=[
                ('idKlient', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('pesel', models.CharField(max_length=11)),
                ('nrKontaktowy', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ksiazka',
            fields=[
                ('idKsiazka', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=45)),
                ('rokWydania', models.DateField()),
                ('cena', models.FloatField()),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprzedazKsiazek.autor')),
                ('idKategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprzedazKsiazek.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='pracownik',
            fields=[
                ('idPracownik', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('pesel', models.CharField(max_length=11)),
                ('nrKontaktowy', models.CharField(max_length=12)),
                ('zarobki', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='zamowienia',
            fields=[
                ('idZamowienia', models.AutoField(primary_key=True, serialize=False)),
                ('cena', models.FloatField()),
                ('idKlient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprzedazKsiazek.klient')),
                ('idKsiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprzedazKsiazek.ksiazka')),
                ('idPracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprzedazKsiazek.pracownik')),
            ],
        ),
    ]
